SetName("vic_rose")

KeyPress(Key.E)
Sleep(100)
KeyDown(Key.Right)
Sleep(500)
KeyPress(Key.Space)
KeyPress(Key.Space)
Sleep(2000)
KeyUp(Key.Right)
Sleep(500)
KeyPress(Key.Space)
Sleep(1000)
WalkAsync(Direction.Backward, 40)
Walk(Direction.Left, 40)
WalkAsync(Direction.Right, 16)
Walk(Direction.Forward, 16)
Walk(Direction.Forward, 52)
Walk(Direction.Right, 24)
Walk(Direction.Backward, 52)
Walk(Direction.Right, 24)
Walk(Direction.Forward, 52)
Walk(Direction.Right, 24)
Walk(Direction.Backward, 52)
Walk(Direction.Right, 24)
Walk(Direction.Forward, 52)
