SetName("vic_cactus")

Sleep(500)
KeyPress(Key.E)
Sleep(100)
KeyDown(Key.Right)
KeyDown(Key.Backward)
Sleep(1000)
KeyPress(Key.Space)
KeyPress(Key.Space)
Sleep(1800)
KeyUp(Key.Right)
KeyUp(Key.Backward)
KeyPress(Key.Space)
Sleep(1000)

Walk(Direction.Forward, 8)
Walk(Direction.Left, 16)
Walk(Direction.Backward, 20)
Walk(Direction.Forward, 12)
Walk(Direction.Right, 16)
Walk(Direction.Backward, 36)
Walk(Direction.Right, 24)
Walk(Direction.Forward, 36)
Walk(Direction.Right, 24)
Walk(Direction.Backward, 36)
Walk(Direction.Right, 24)
Walk(Direction.Forward, 36)
Walk(Direction.Right, 24)
Walk(Direction.Backward, 36)