SetName("vic_pepper")

Walk(Direction.Right, 70.0)
Walk(Direction.Left, 2.0)
Sleep(50)
KeyPress(Key.Space)
KeyPress(Key.Space)
Sleep(50)

Walk(Direction.Right, 22)
Walk(Direction.Forward, 14)
Walk(Direction.Backward, 2.0)
Sleep(50)

KeyPress(Key.Space)
KeyPress(Key.Space)

Sleep(100)

Walk(Direction.Forward, 58)
KeyDown(Key.Forward)
Walk(Direction.Right, 20)

KeyPress(Key.Space)
Sleep(800)
KeyPress(Key.Space)
Sleep(1800)
KeyPress(Key.Space)
Sleep(2500)

KeyDown(Key.Right)
Sleep(1000)
KeyUp(Key.Forward)

KeyPress(Key.Space)
KeyPress(Key.Space)
Sleep(4000)
KeyPress(Key.Space)
Sleep(200)
KeyUp(Key.Right)
KeyDown(Key.Backward)
Sleep(2500)
KeyUp(Key.Backward)
KeyDown(Key.Forward)
Sleep(1250)
KeyUp(Key.Forward)
KeyDown(Key.Right)
Sleep(800)
KeyUp(Key.Right)
Walk(Direction.Forward, 64)
Walk(Direction.Right, 22)
Walk(Direction.Backward, 74)
Walk(Direction.Right, 22)
Walk(Direction.Forward, 74)
