// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['main']['Macro']['DeleteAccount'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['Macro']['DeletePreset'](arg1);
}

export function GetLoginCode() {
  return window['go']['main']['Macro']['GetLoginCode']();
}

export function Pause(arg1) {
  return window['go']['main']['Macro']['Pause'](arg1);
}

export function PauseAll() {
  return window['go']['main']['Macro']['PauseAll']();
}

export function ReceiveCommand(arg1) {
  return window['go']['main']['Macro']['ReceiveCommand'](arg1);
}

export function SetAccountPreset(arg1, arg2) {
  return window['go']['main']['Macro']['SetAccountPreset'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['main']['Macro']['Start'](arg1);
}

export function StartAll() {
  return window['go']['main']['Macro']['StartAll']();
}

export function StartRelay(arg1) {
  return window['go']['main']['Macro']['StartRelay'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['Macro']['Stop'](arg1);
}

export function StopAll() {
  return window['go']['main']['Macro']['StopAll']();
}

export function StopRelay(arg1) {
  return window['go']['main']['Macro']['StopRelay'](arg1);
}
