// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings(arg1) {
  return window['go']['main']['Macro']['LoadSettings'](arg1);
}

export function LoadState(arg1) {
  return window['go']['main']['Macro']['LoadState'](arg1);
}

export function Pause() {
  return window['go']['main']['Macro']['Pause']();
}

export function PauseAll() {
  return window['go']['main']['Macro']['PauseAll']();
}

export function Resume() {
  return window['go']['main']['Macro']['Resume']();
}

export function ResumeAll() {
  return window['go']['main']['Macro']['ResumeAll']();
}

export function SetActiveInstance() {
  return window['go']['main']['Macro']['SetActiveInstance']();
}
