// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRelay(arg1:string,arg2:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<string>;

export function DeletePreset(arg1:string):Promise<string>;

export function DownloadDataset():Promise<void>;

export function GetLoginCode():Promise<string>;

export function Pause(arg1:string):Promise<void>;

export function PauseAll():Promise<void>;

export function ReceiveCommand(arg1:Array<string>):Promise<boolean>;

export function SetAccountPreset(arg1:string,arg2:string):Promise<string>;

export function Start(arg1:string):Promise<void>;

export function StartAll():Promise<void>;

export function StartRelay(arg1:string):Promise<string>;

export function Stop(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopRelay(arg1:string):Promise<void>;
