// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function LoadSettings(arg1:string):Promise<config.Settings>;

export function LoadState(arg1:string):Promise<config.MacroState>;

export function Pause():Promise<void>;

export function PauseAll():Promise<void>;

export function Resume():Promise<void>;

export function ResumeAll():Promise<void>;

export function SetActiveInstance():Promise<void>;
