// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePreset() {
  return window['go']['main']['Macro']['CreatePreset']();
}

export function Pause(arg1) {
  return window['go']['main']['Macro']['Pause'](arg1);
}

export function PauseAll() {
  return window['go']['main']['Macro']['PauseAll']();
}

export function Resume(arg1) {
  return window['go']['main']['Macro']['Resume'](arg1);
}

export function ResumeAll() {
  return window['go']['main']['Macro']['ResumeAll']();
}
